// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSLtYRhnK-yCZJ5IFA9RPXYHBUPI5xSto',
    appId: '1:520547123248:web:9c4086b1b200fa28f8edf5',
    messagingSenderId: '520547123248',
    projectId: 'netflix-clone-b3d51',
    authDomain: 'netflix-clone-b3d51.firebaseapp.com',
    storageBucket: 'netflix-clone-b3d51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8g_jBftVM8331Zb995aP0bmu9kem5sk',
    appId: '1:520547123248:android:afe5dd53c929bb2ff8edf5',
    messagingSenderId: '520547123248',
    projectId: 'netflix-clone-b3d51',
    storageBucket: 'netflix-clone-b3d51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl2UZCy0ls6216PJFo56aTrZx1efQ8dhU',
    appId: '1:520547123248:ios:89650ded2620bea6f8edf5',
    messagingSenderId: '520547123248',
    projectId: 'netflix-clone-b3d51',
    storageBucket: 'netflix-clone-b3d51.appspot.com',
    iosBundleId: 'com.example.netflixClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl2UZCy0ls6216PJFo56aTrZx1efQ8dhU',
    appId: '1:520547123248:ios:57d694530c359135f8edf5',
    messagingSenderId: '520547123248',
    projectId: 'netflix-clone-b3d51',
    storageBucket: 'netflix-clone-b3d51.appspot.com',
    iosBundleId: 'com.example.netflixClone.RunnerTests',
  );
}
